import Vue from 'vue'
import { Checkbox, Rate, Icon, Button, Picker, Tabbar, TabbarItem, NavBar, Toast, GridItem, SwipeItem, Search, Swipe, Grid, ActionSheet, Dialog, Tab, Tabs } from 'vant'

Vue.use(Tab)
Vue.use(Tabs)
Vue.use(Checkbox)
Vue.use(Dialog)
Vue.use(ActionSheet)
Vue.use(Icon)
Vue.use(Rate)
Vue.use(Search)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Toast)
Vue.use(NavBar)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(Picker)
Vue.use(Button)
